### ISSUE TITLE
Serviceprincipal layout changed.

### ISSUE THREAD

**Issue by bjompen** [Ba4bes/New-AzDoServiceConnection#2]
Since this command was written it seems there has been a change in the layout of the ServicePrincipal object used.

- ApplicationId has been renamed AppId
- The plaintextsecret is now available directly in PasswordCredentials.SecretText

Since this command is connected to a bloggpost (most excelent one, as always!) I don't know if you want to update the command,
but if you want a PR is incoming.

Disclaimer: I have not verified the changes in PowerShell 5.1, and have not changed the if/else statement,
but since this is an endpoint change in Azure I imagine you could get rid of the entire if/else block and just use the variable in line 168.

//Björn

**Comment by Ba4bes** [comment]
Fixed by #3
